export interface OperadoraInterface {
	registroAns: string,
	cnpj: string,
	razaoSocial: string,
	nomeFantasia: string,
	modalidade: string,
	logradouro: string,
	numero: string,
	complemento: string,
	bairro: string,
	cidade: string,
	uf: string,
	cep: string,
	ddd: string,
	telefone: string,
	fax: string,
	enderecoEletronico: string,
	representante: string,
	cargoRepresentante: string,
	regiaoDeComercializacao: number,
	dataRegistroAns: Date
}